services:
  portal:
    image: ${DOCKER_REGISTRY-}portal
    container_name: portal-app
    build:
      context: .
      dockerfile: Portal/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"
    environment:
    - POSTGRES_DB=portal
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
    - portal-db

  portal-db:
    image: postgres
    container_name: portal-db
    environment:
    - POSTGRES_DB=portal
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - ./.containers/portal-db:/var/lib/postgresql/data
    ports:
    - "54320:5432"
    